services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: uwork_api_dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: development
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./tsconfig.json:/app/tsconfig.json
    ports:
      - "3000:3000"
    networks:
      - uwork_network

networks:
  uwork_network:
    driver: bridge
